name: FuriousEncantamentos
version: '1.0-SNAPSHOT'
main: org.furious.furiousencantamentos.FuriousEncantamentos
description: Plugin customizado de encantamentos para a Rede Furious
commands:
  rlencantamentos:
    description: Recarregar o arquivo do yml de encantamentos
    permission-message: "§cVocê não tem permissão para usar o comando '/rlencantamentos'."
    aliases: [ rle, reloade, rlenchant, encantamentosreload ]